### ISSUE TITLE
Month Navigation

### ISSUE THREAD

**Issue by darrellc** [twinssbc/Ionic2-Calendar#79] opened 2017-03-29 19:12 UTC
I would like to navigate months using arrow navigation buttons.  How would I do interface with the calendar monthview to slide the month.

**Comment by twinssbc** [comment] 2017-03-30 00:12
@darrellc You can change currentDate to the date in previous/next month.

**Comment by darrellc** [comment] 2017-03-30 12:43
HTML

`<ion-grid>
      <ion-row>
            <ion-col col-3 class="calendar-button back">
                <button ion-button icon-only (click)="changeMonth('back')">
                    <ion-icon name="arrow-back"></ion-icon>
                </button>
            </ion-col>
            <ion-col col-6>
                <h5>{{ calendar.monthName }}</h5>
            </ion-col>
            <ion-col col-3 class="calendar-button forward">
                <button ion-button icon-only (click)="changeMonth('forward')">
                    <ion-icon name="arrow-forward"></ion-icon>
                </button>
            </ion-col>
      </ion-row>
  </ion-grid>
  <calendar 
    [eventSource]="calendar.events" 
    [calendarMode]="calendar.mode" 
    [currentDate]="calendar.currentDate" 
    (onCurrentDateChanged)="onCurrentDateChanged($event)"  
    (onRangeChanged)="onRangeChanged()"
    step="30" 
    formatDayHeader="E"></calendar>`

TYPESCRIPT

**Comment by darrellc** [comment] 2017-03-30 13:05
I did change the current date, but no refresh of the calendar.

`changeMonth(direction){
    console.log(this.calendar);
    switch(direction){
      case "back":
        this.calendar.currentDate.setMonth(this.currentMonth - 1);
        break;
      case "forward":
        this.calendar.currentDate.setMonth(this.currentMonth + 1);
        break;
    }
    console.log(this.calendar["currentDate"]);
    return this.calendar;
  }`

**Comment by twinssbc** [comment] 2017-03-30 15:42
@darrellc You need to assign it back to the currentDate variable.
```
this.calendar.currentDate = new Date(this.calendar.currentDate.setMonth(this.currentMonth - 1));
```

**Comment by rosehashmi** [comment] 2017-06-24 10:02
Actually i want to change the date using navigation buttons. 'this.calendar.currentDate' is not updating only if i change the calendar view. is there any way to swipe left and right using navigation buttons?

**Comment by twinssbc** [comment] 2017-06-25 00:04
@rosehashmi It should work. Could you provide your code in your navigation button callback?
Basically you just need to set the currentDate in your callback. The calendar will navigate to the corresponding month. It's also possible that you are assigning the currentDate to different object? Not the object bound to the calendar.

**Comment by newbie-ionic** [comment] 2017-06-26 19:47
Hi @twinssbc,
I am very new to Ionic. I am trying to show week view. But I want navigation for month also. How could I achieve that? Can you please send me source code so it will be very helpful for me.

**Comment by twinssbc** [comment] 2017-06-27 01:30
@newbie-ionic You want to navigate by month in the weekview? I suppose you will have some button to let you select the month. Then in the click callback method, you just need to set the currentDate to a date in the selected month.

**Comment by newbie-ionic** [comment] 2017-06-27 08:50
Hi @twinssbc,
Thank you for replying. I have written one click event on previous button to which I have set previous month date. But calendar view is not rendering as per month. It is showing same week view.

**Comment by twinssbc** [comment] 2017-06-27 10:10
@newbie-ionic Could you provide your code that is changing the date in the click callback method?

**Comment by newbie-ionic** [comment] 2017-06-27 10:33
I have taken one button for previous month view. 

previousMonthButton() {
    this.calendar.currentDate = new Date(this.calendar.currentDate.setMonth(this.myDate.getMonth() - 1));
  }

**Comment by twinssbc** [comment] 2017-06-27 14:39
@newbie-ionic I just tested that it's working. Is it possible something wrong with this.myDate?

**Comment by newbie-ionic** [comment] 2017-06-27 14:47
Can you please tell me what is wrong with code? It will be really helpful for me. Your help will be appreciated.

**Comment by newbie-ionic** [comment] 2017-06-27 14:53
I have declared myDate = new Date();
I am able to get previous month title which is bind to {{viewTitle}}. But when I click on previous month, I am able to see days from 1 to 7 of previous month. Other days are not displaying. It will show next month's days directly.

**Comment by twinssbc** [comment] 2017-06-27 15:37
The problem is myDate never changes?
Below code is working in my project
```
this.calendar.currentDate = new Date(this.calendar.currentDate.setMonth(this.calendar.currentDate.getMonth() - 1));
```

**Comment by newbie-ionic** [comment] 2017-06-28 05:57
Thank you @twinssbc.

**Comment by chethangowda** [comment] 2017-09-15 05:54
@twinssbc  I want to refresh the calendar onSwipe left and right, which method will get hit on swipe
Help me out here...

**Comment by twinssbc** [comment] 2017-09-16 13:17
@chethangowda onRangeChanged will be triggered if you set the queryMode to 'remote'.

**Closed** 2018-01-18 00:24 UTC

**Comment by NIYASSURABHI** [comment] 2019-12-03 05:51
What will happens if i click navigation button from 31 January to February? it is coming to march 2. How can handle this?
